# Generated by Django 3.1.4 on 2020-12-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_questions_quiz_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='title',
        ),
    ]
