# Generated by Django 3.1.4 on 2020-12-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20201222_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='choice',
            new_name='choice_desc',
        ),
    ]
