# Generated by Django 3.1.4 on 2020-12-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_auto_20201223_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='quiz_id',
            new_name='quiz',
        ),
    ]
