# Generated by Django 3.1.4 on 2020-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_auto_20201224_0526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
