# Generated by Django 3.1.4 on 2020-12-24 18:21

from django.db import migrations, models
import quiz_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0014_auto_20201224_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquiztrack',
            name='end_time',
            field=models.FloatField(default=quiz_app.models.getTimeNow),
        ),
    ]
