# Generated by Django 3.1.4 on 2020-12-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0015_auto_20201224_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquiztrack',
            old_name='Score',
            new_name='score',
        ),
    ]
