# Generated by Django 3.1.4 on 2020-12-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0016_auto_20201224_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquesanstrack',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.student'),
            preserve_default=False,
        ),
    ]
